name: novaboard-scheduling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests
  - python-dotenv
  - pytest
  - pytest-cov
  - black
  - flake8
  - pandas
  - timm
  - pip:
    - pydantic
    - httpx
    - "plotly[express]"
    - kaleido
    - opencv-python>=4.8.0
    - google-generativeai==0.3.2
