"""
schedule_message.py
-------------------
Generates a production planner approval message from a resolved schedule.
Designed to be channel-agnostic — returns a plain string you can send
via Telegram, Slack, Discord, or any other messaging integration.

Expected input shape
--------------------
scheduled_orders: list of dicts, already sorted in execution order, e.g.:

    [
        {
            "so_id": "SO-001",
            "customer": "IndustrialCore",
            "product_code": "PCB-IND-100",
            "quantity": 2,
            "starts_at": datetime(2026, 2, 28, 8, 0),
            "ends_at": datetime(2026, 2, 28, 12, 54),
            "deadline": datetime(2026, 3, 2, 17, 0),
            "priority": 1,
            "deadline_met": True,
        },
        ...
    ]

edf_overrides (auto-generated by detect_edf_overrides): list of dicts, one per
higher-priority order that was pushed back, e.g.:

    [
        {
            "pushed_back": { <order dict for SO-005> },
            "scheduled_before": [ <order dict for SO-003>, <order dict for SO-004>, ... ],
        }
    ]
"""

from datetime import datetime


def _fmt_dt(dt: datetime) -> str:
    """Mar 2 08:00"""
    return dt.strftime("%b %-d %H:%M")


def _fmt_deadline(dt: datetime) -> str:
    """Mar 2"""
    return dt.strftime("%b %-d")


def detect_edf_overrides(scheduled_orders: list[dict]) -> list[dict]:
    """
    For each higher-priority order, find all lower-priority orders
    scheduled before it and group them into a single override entry.

    Returns one override per "victim" (higher-priority order that got pushed
    back), listing all lower-priority orders ahead of it.
    """
    overrides = []
    for j, later in enumerate(scheduled_orders):
        lower_priority_before = [
            o for o in scheduled_orders[:j]
            if o["priority"] > later["priority"]
        ]
        if lower_priority_before:
            overrides.append({
                "pushed_back": later,
                "scheduled_before": lower_priority_before,
            })
    return overrides


def _edf_override_text(override: dict) -> str:
    pushed = override["pushed_back"]
    before = override["scheduled_before"]

    # Build a compact list of the orders scheduled before it
    before_str = ", ".join(
        f"{o['so_id']} (deadline {_fmt_deadline(o['deadline'])})"
        for o in before
    )

    return (
        f"  • {before_str} is scheduled before "
        f"{pushed['so_id']} (deadline {_fmt_deadline(pushed['deadline'])}) "
        f"despite {pushed['so_id']} being P{pushed['priority']} — "
        f"EDF prioritises tighter deadlines. All deadlines are met."
    )


def _order_line(index: int, order: dict) -> str:
    status = "✅" if order["deadline_met"] else "❌ LATE"
    return (
        f"{index}. {order['so_id']} · {order['customer']} · "
        f"{order['product_code']} ×{order['quantity']} · "
        f"{_fmt_dt(order['starts_at'])} → {_fmt_dt(order['ends_at'])} · "
        f"due {_fmt_deadline(order['deadline'])} {status}"
    )


def build_schedule_message(
    scheduled_orders: list[dict],
    run_date: datetime | None = None,
    collapse_after: int | None = None,
) -> str:
    """
    Build the approval message string.
    EDF overrides are detected automatically from the scheduled order list.

    Parameters
    ----------
    scheduled_orders : list of order dicts in execution order
    run_date         : defaults to today
    collapse_after   : orders beyond this index are summarised, not listed.
                       Defaults to None (always show all orders, as per spec).
    """
    run_date = run_date or datetime.now()
    total = len(scheduled_orders)
    at_risk = [o for o in scheduled_orders if not o["deadline_met"]]
    edf_overrides = detect_edf_overrides(scheduled_orders)

    # ── Header ──────────────────────────────────────────────────────────────
    deadline_summary = (
        "All deadlines met ✅"
        if not at_risk
        else f"{len(at_risk)} deadline(s) at risk ❌: "
        + ", ".join(o["so_id"] for o in at_risk)
    )

    lines = [
        f"📋 *Production Schedule — {run_date.strftime('%b %-d, %Y')}*",
        f"{total} orders · {deadline_summary} · Awaiting your approval",
    ]

    # ── EDF override explanations ────────────────────────────────────────────
    if edf_overrides:
        lines.append("")
        lines.append("⚠️ *Scheduling note*")
        for override in edf_overrides:
            lines.append(_edf_override_text(override))

    # ── Order sequence ───────────────────────────────────────────────────────
    lines.append("")
    lines.append("*Sequence*")

    visible = (
        scheduled_orders
        if collapse_after is None
        else scheduled_orders[:collapse_after]
    )

    for i, order in enumerate(visible, start=1):
        lines.append(_order_line(i, order))

    remaining = scheduled_orders[collapse_after:] if collapse_after else []
    if remaining:
        remaining_met = all(o["deadline_met"] for o in remaining)
        remaining_status = "all within deadline ✅" if remaining_met else "⚠️ check details"
        lines.append(
            f"{collapse_after + 1}–{total}. "
            f"({len(remaining)} further orders, {remaining_status})"
        )

    # ── Call to action ───────────────────────────────────────────────────────
    lines.append("")
    lines.append("Reply *APPROVED* to confirm or describe any changes.")

    return "\n".join(lines)


# ── Example usage ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    sample_orders = [
        {
            "so_id": "SO-001",
            "customer": "IndustrialCore",
            "product_code": "PCB-IND-100",
            "quantity": 2,
            "starts_at": datetime(2026, 2, 28, 8, 0),
            "ends_at": datetime(2026, 2, 28, 12, 54),
            "deadline": datetime(2026, 3, 2, 17, 0),
            "priority": 1,
            "deadline_met": True,
        },
        {
            "so_id": "SO-002",
            "customer": "MedTec Devices",
            "product_code": "MED-300",
            "quantity": 1,
            "starts_at": datetime(2026, 2, 28, 12, 54),
            "ends_at": datetime(2026, 2, 28, 17, 33),
            "deadline": datetime(2026, 3, 3, 17, 0),
            "priority": 1,
            "deadline_met": True,
        },
        {
            "so_id": "SO-009",
            "customer": "MedTec Devices",
            "product_code": "MED-300",
            "quantity": 3,
            "starts_at": datetime(2026, 3, 1, 8, 0),
            "ends_at": datetime(2026, 3, 2, 15, 30),
            "deadline": datetime(2026, 3, 4, 17, 0),
            "priority": 1,
            "deadline_met": True,
        },
        {
            "so_id": "SO-003",
            "customer": "AgriBot Systems",
            "product_code": "AGR-400",
            "quantity": 5,
            "starts_at": datetime(2026, 3, 2, 15, 30),
            "ends_at": datetime(2026, 3, 3, 15, 30),
            "deadline": datetime(2026, 3, 4, 17, 0),
            "priority": 2,
            "deadline_met": True,
        },
        {
            "so_id": "SO-005",
            "customer": "SmartHome IoT",
            "product_code": "IOT-200",
            "quantity": 10,
            "starts_at": datetime(2026, 3, 3, 15, 30),
            "ends_at": datetime(2026, 3, 4, 15, 30),
            "deadline": datetime(2026, 3, 8, 17, 0),
            "priority": 1,
            "deadline_met": True,
        },
        # remaining orders abbreviated for brevity
    ]

    msg = build_schedule_message(
        scheduled_orders=sample_orders,
        run_date=datetime(2026, 2, 28),
        collapse_after=5,
    )

    print(msg)
